title = "WI Mods"
baseurl = "https://www.wimods.net/"
DefaultContentLanguage = "en"
titleCaseStyle = "none"

[privacy]
  [privacy.googleAnalytics]
    disable = true
  [privacy.x]
    disable = false
    enableDNT = true
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = true

[markup.goldmark.renderer]
  unsafe = true

[taxonomies]
  mcversion = "mcversions"
  snapshot = "snapshots"

[Params]
  [Params.modnames]
    mo-glass = "Mo Glass"
    wi-zoom = "WI Zoom"
    cameranoclip = "CameraNoClip"
    chestesp = "ChestESP"
  [Params.modloader_names]
    fabric = "Fabric"
    neoforge = "NeoForge"
    forge = "Forge"
  [Params.fabric_suffix]
    cameranoclip = "-Fabric"
    chestesp = "-Fabric"
  [Params.mc_version_aliases]
    "1.21.5" = "1.21.5 / 25.1"
    "1.21.6" = "1.21.6 / 25.2"
    "1.21.7" = "1.21.7 / 25.2.1"
    "1.21.8" = "1.21.8 / 25.2.2"
    "1.21.9" = "1.21.9 / 25.3"
    "1.21.10" = "1.21.10 / 25.3.1"
    "1.21.11" = "1.21.11 / 25.4"
  [Params.mc_update_names]
    "1.12.2" = "The World of Color Update"
    "1.14.4" = "The Village & Pillage Update"
    "1.15" = "The Buzzy Bees Update"
    "1.15.1" = "The Buzzy Bees Update"
    "1.15.2" = "The Buzzy Bees Update"
    "1.16" = "The Nether Update"
    "1.16.1" = "The Nether Update"
    "1.16.2" = "The Nether Update"
    "1.16.3" = "The Nether Update"
    "1.16.4" = "The Nether Update"
    "1.16.5" = "The Nether Update"
    "1.17" = "Caves & Cliffs Part 1"
    "1.17.1" = "Caves & Cliffs Part 1"
    "1.18" = "Caves & Cliffs Part 2"
    "1.18.1" = "Caves & Cliffs Part 2"
    "1.18.2" = "Caves & Cliffs Part 2"
    "1.19" = "The Wild Update"
    "1.19.1" = "The Chat Reports Update"
    "1.19.2" = "The Chat Reports Update"
    "1.19.3" = "The Wild Update"
    "1.19.4" = "The Wild Update"
    "1.20" = "The Trails & Tales Update"
    "1.20.1" = "The Trails & Tales Update"
    "1.20.2" = "The Trails & Tales Update"
    "1.20.3" = "The Trails & Tales Update"
    "1.20.4" = "The Trails & Tales Update"
    "1.20.5" = "The Armored Paws Drop"
    "1.20.6" = "The Armored Paws Drop"
    "1.21" = "The Tricky Trials Update"
    "1.21.1" = "The Tricky Trials Update"
    "1.21.2" = "The Bundles of Bravery Drop"
    "1.21.3" = "The Bundles of Bravery Drop"
    "1.21.4" = "The Garden Awakens Drop"
    "1.21.5" = "The Spring To Life Drop (25.1)"
    "1.21.6" = "Chase The Skies (25.2)"
    "1.21.7" = "The Lava Chicken Drop (25.2.1)"
    "1.21.8" = "The Lava Chicken Drop (25.2.2)"
    "1.21.9" = "The Copper Age (25.3)"
    "1.21.10" = "Copper Age Hotfix 1 (25.3.1)"
    "1.21.11" = "Mounts of Mayhem (25.4)"

[permalinks]
  redirect = "/:sections[1:]/:slugorcontentbasename"
